Merge initial js-lib-redux-state-history
paysera/js-lib-redux-state-history pull request #1
Opened 2019-10-22 13:57 UTC by romasnavasinskas

2019-10-22 14:03 UTC, vbartusevicius requested changes

2019-10-22 14:03 UTC, vbartusevicius commented on package.json
> +  "name": "@paysera/error-message-resolver",
`error-message-resolver` ?

2019-10-22 14:03 UTC, vbartusevicius commented on package.json
> +    "redux-actions": "^2.6.5"
isn't `redux` aslo a dependency? - I see you're using `store.dispatch` somewhere

2019-10-22 16:31 UTC, romasnavasinskas commented on package.json
> +  "name": "@paysera/error-message-resolver",
Sorry, was using our another library as a guide/boilerplate to bootstrap common configurations that we usually use for javascript libraries. Copied common `package.json` configurations, this must have slipped through.

2019-10-23 07:13 UTC, vbartusevicius requested changes

2019-10-23 07:13 UTC, vbartusevicius commented on package.json
> +  "main": "dist/main.js",
I don't see `dist/*` in this PR

2019-10-23 08:57 UTC, merged